kind: pipeline
name: drone
steps:
  - name: test
    image: busybox
    commands:
      - nslookup google.com
    dns: [ 114.114.114.114 ]

  - name: build
    dns: [ 114.114.114.114 ]
    image: plugins/docker
    repo: testApp/testApp
