kind: pipeline
name: drone
steps:
  - name: npm-install
    image: node:10
    commands:
      - pwd
      - npm config set cache ./.npm-cache --global
      - npm install
    volumes:
      - name: cache
        path: /82253452/healthy-app/node_modules

  - name: build-dist
    image: node:10
    commands:
      - npm run build

  - name: build
    image: plugins/docker
    settings:
      username: cn-north-1@8BKNSGZGCNYMTOUZR9YS
      password: e119c7e6f7a4572454fa96f7b8b6fa34d37a00e7e16caa3274b69c0c6eeded7b
      registry: swr.cn-north-1.myhuaweicloud.com
      repo: swr.cn-north-1.myhuaweicloud.com/a82253452/myapp
      auto_tag: true

  - name: code-scp
    image: appleboy/drone-scp
    settings:
      host: 114.115.250.201
      username: root
      password: Sdfasiwek2#@8123
      port: 222
      target: /projects/myapp
      source: docker-compose.yml

  - name: code-deploy
    image: appleboy/drone-ssh
    settings:
      host: 114.115.250.201
      username: root
      password: Sdfasiwek2#@8123
      port: 222
      script:
        - cd /projects/myapp
        - docker-compose pull
        - docker-compose up -d --force-recreate

volumes:
  - name: cache
    host:
      path: /tmp/cache
