version: "3"
networks:
  default:
    external:
      name: default-network
services:
  myapp:
    container_name: drone-myapp
    image: swr.cn-north-1.myhuaweicloud.com/a82253452/myapp
    ports:
      - 8011:80
